### ISSUE TITLE
Accordion Off doesn't work in the demo?

### ISSUE THREAD

**Issue by jimthedev** [heroqu/react-accordion-composable#1]
Accordion Off doesn't work in the demo? 

Seems like you can still click it after off.

**Comment by heroqu** [comment]
Hi,

Thanks for reply,

Accordion Off means there is no mutual dependency between sections: they 
still can be expanded / collapsed but expanding one section doesn't 
collapse the previously expanded one any longer. It doesn't mean 
freezing all sections in collapsed state.

Sorry if I haven't make it that clear and thank you for pointing on 
this. I've just edited the demo page and hope now it's more clear in 
regard of Accordion modes of operation.

Best regards

**Comment by jimthedev** [comment]
Ah ok now I see what you meant. Maximum one expansion vs unlimited expansion. Thanks!
